// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260813081436_Spam2")]
    partial class Spam2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastEditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recipients")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("Domain.Models.Letter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ForwardRecipientId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Forwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("OriginalAuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentLetterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("ForwardRecipientId");

                    b.HasIndex("OriginalAuthorId");

                    b.HasIndex("ParentLetterId");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("Domain.Models.LetterState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpam")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Starred")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LetterId");

                    b.HasIndex("UserId");

                    b.ToTable("LetterStates");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMan")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SpamEmails")
                        .HasColumnType("text[]");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LetterUser", b =>
                {
                    b.Property<Guid>("AcceptLettersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipientsId")
                        .HasColumnType("uuid");

                    b.HasKey("AcceptLettersId", "RecipientsId");

                    b.HasIndex("RecipientsId");

                    b.ToTable("LetterUser");
                });

            modelBuilder.Entity("Domain.Models.Draft", b =>
                {
                    b.HasOne("Domain.User", "Author")
                        .WithMany("Drafts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Domain.Models.Letter", b =>
                {
                    b.HasOne("Domain.User", "Addressee")
                        .WithMany("SentLetters")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "ForwardRecipient")
                        .WithMany()
                        .HasForeignKey("ForwardRecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.User", "OriginalAuthor")
                        .WithMany()
                        .HasForeignKey("OriginalAuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.Letter", "ParentLetter")
                        .WithMany("ChildrenLetters")
                        .HasForeignKey("ParentLetterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Addressee");

                    b.Navigation("ForwardRecipient");

                    b.Navigation("OriginalAuthor");

                    b.Navigation("ParentLetter");
                });

            modelBuilder.Entity("Domain.Models.LetterState", b =>
                {
                    b.HasOne("Domain.Models.Letter", "Letter")
                        .WithMany("LetterStates")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("LetterStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Letter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LetterUser", b =>
                {
                    b.HasOne("Domain.Models.Letter", null)
                        .WithMany()
                        .HasForeignKey("AcceptLettersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Letter", b =>
                {
                    b.Navigation("ChildrenLetters");

                    b.Navigation("LetterStates");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("LetterStates");

                    b.Navigation("SentLetters");
                });
#pragma warning restore 612, 618
        }
    }
}
